// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPBTLhujDzgOsn0gNNo2OrY1GCAJG5q8',
    appId: '1:938412593336:web:d0c758dcb94e162da6644d',
    messagingSenderId: '938412593336',
    projectId: 'big-meat-mart-a2902',
    authDomain: 'big-meat-mart-a2902.firebaseapp.com',
    storageBucket: 'big-meat-mart-a2902.appspot.com',
    measurementId: 'G-Z81DYJ08DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexGqWngA6iu3hmm1ETuy0u-et8eh62oI',
    appId: '1:938412593336:android:160178bbb212e07ba6644d',
    messagingSenderId: '938412593336',
    projectId: 'big-meat-mart-a2902',
    storageBucket: 'big-meat-mart-a2902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV3C1mNVKGxwzSuPTMWcBXnJU1Z4U8tZA',
    appId: '1:938412593336:ios:448ca1e52c22022fa6644d',
    messagingSenderId: '938412593336',
    projectId: 'big-meat-mart-a2902',
    storageBucket: 'big-meat-mart-a2902.appspot.com',
    iosClientId: '938412593336-or1c5ukskeb1vh7p8ce1h15385g4qdbj.apps.googleusercontent.com',
    iosBundleId: 'com.bigmeatmart.app',
  );
}
